#=============================================================================
# dark_powered.toml --- dark powered configuration example for SpaceVim
# Copyright (c) 2016-2021 Wang Shidong & Contributors
# Author: Wang Shidong < wsdjeg at 163.com >
# URL: https://spacevim.org
# License: GPLv3
#=============================================================================

# All SpaceVim option below [option] section
[options]
    # set spacevim theme. by default colorscheme layer is not loaded,
    # if you want to use more colorscheme, please load the colorscheme
    # layer
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    # Disable guicolors in basic mode, many terminal do not support 24bit
    # true colors
    enable_guicolors = true
    # Disable statusline separator, if you want to use other value, please
    # install nerd fonts
    statusline_separator = "arrow"
    statusline_iseparator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false

# Enable autocomplete layer
[[layers]]
name = 'autocomplete'
auto_completion_return_key_behavior = "complete"
auto_completion_tab_key_behavior = "smart"

[[layers]]
name = 'shell'
default_position = 'top'
default_height = 30

[[layers]]
  name = "lang#csharp"
  highlight_types = 0

[[custom_plugins]]
    repo = "lilydjwg/colorizer"
    merged = false
 
  [options]
  autocomplete_method = "coc"

# The lsp layer has to be enabled too. SpaceVim converts the configuration in the lsp layer and then passes it to coc.
# You can put your language servers here.
[[layers]] 
  name = 'lsp'
  filetypes = [
#   'c',
#   'cpp',
#   'dart',
    'cs'
  ]
  [layers.override_cmd]
#    c = ['ccls', '--log-file=/tmp/ccls.log']
#cpp = ['ccls', '--log-file=/tmp/ccls.log']
    cs = ['omnisharp', '--log-file=/tmp/omnisharp.log']

